import BlocksAPI from '@repo/editor/components/modules/api/blocks';
import CaretAPI from '@repo/editor/components/modules/api/caret';
import EventsAPI from '@repo/editor/components/modules/api/events';
import I18nAPI from '@repo/editor/components/modules/api/i18n';
import API from '@repo/editor/components/modules/api/index';
import InlineToolbarAPI from '@repo/editor/components/modules/api/inline-toolbar';
import ListenersAPI from '@repo/editor/components/modules/api/listeners';
import NotifierAPI from '@repo/editor/components/modules/api/notifier';
import ReadOnlyAPI from '@repo/editor/components/modules/api/readonly';
import SanitizerAPI from '@repo/editor/components/modules/api/sanitizer';
import SaverAPI from '@repo/editor/components/modules/api/saver';
import SelectionAPI from '@repo/editor/components/modules/api/selection';
import StylesAPI from '@repo/editor/components/modules/api/styles';
import ToolbarAPI from '@repo/editor/components/modules/api/toolbar';
import TooltipAPI from '@repo/editor/components/modules/api/tooltip';
import UiAPI from '@repo/editor/components/modules/api/ui';
import BlockSettings from '@repo/editor/components/modules/toolbar/block-settings';
import Toolbar from '@repo/editor/components/modules/toolbar/index';
import InlineToolbar from '@repo/editor/components/modules/toolbar/inline';
import BlockEvents from '@repo/editor/components/modules/block-events';
import BlockManager from '@repo/editor/components/modules/block-manager';
import BlockSelection from '@repo/editor/components/modules/block-selection';
import Caret from '@repo/editor/components/modules/caret';
import CrossBlockSelection from '@repo/editor/components/modules/cross-block-selection';
import DragNDrop from '@repo/editor/components/modules/drag-n-drop';
import ModificationsObserver from '@repo/editor/components/modules/modifications-observer';
import Paste from '@repo/editor/components/modules/paste';
import ReadOnly from '@repo/editor/components/modules/readonly';
import RectangleSelection from '@repo/editor/components/modules/rectangle-selection';
import Renderer from '@repo/editor/components/modules/renderer';
import Saver from '@repo/editor/components/modules/saver';
import Tools from '@repo/editor/components/modules/tools';
import UI from '@repo/editor/components/modules/ui';
import ToolsAPI from '@repo/editor/components/modules/api/tools';

export type EditorModules = {
  BlocksAPI: BlocksAPI;
  CaretAPI: CaretAPI;
  ToolsAPI: ToolsAPI;
  EventsAPI: EventsAPI;
  I18nAPI: I18nAPI;
  API: API;
  InlineToolbarAPI: InlineToolbarAPI;
  ListenersAPI: ListenersAPI;
  NotifierAPI: NotifierAPI;
  ReadOnlyAPI: ReadOnlyAPI;
  SanitizerAPI: SanitizerAPI;
  SaverAPI: SaverAPI;
  SelectionAPI: SelectionAPI;
  StylesAPI: StylesAPI;
  ToolbarAPI: ToolbarAPI;
  TooltipAPI: TooltipAPI;
  UiAPI: UiAPI;
  BlockSettings: BlockSettings;
  Toolbar: Toolbar;
  InlineToolbar: InlineToolbar;
  BlockEvents: BlockEvents;
  BlockManager: BlockManager;
  BlockSelection: BlockSelection;
  Caret: Caret;
  CrossBlockSelection: CrossBlockSelection;
  DragNDrop: DragNDrop;
  ModificationsObserver: ModificationsObserver;
  Paste: Paste;
  ReadOnly: ReadOnly;
  RectangleSelection: RectangleSelection;
  Renderer: Renderer;
  Saver: Saver;
  Tools: Tools;
  UI: UI;
};
